//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int idChat { get; set; }
        public int idSala { get; set; }
        public int idUsuario { get; set; }
        public int numero { get; set; }
        public string mensagem { get; set; }
    }
}
