//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat_usuario_sala
    {
        public int usuario_idusuario { get; set; }
        public int sala_idsala { get; set; }
        public int sala_temasala_idtemasala { get; set; }
        public string mensagem { get; set; }
        public int numero { get; set; }
        public int chat_usuario_salacol { get; set; }
    
        public virtual sala sala { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
