//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bancofcEntities : DbContext
    {
        public bancofcEntities()
            : base("name=bancofcEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<biblioteca> biblioteca { get; set; }
        public virtual DbSet<chat_usuario_sala> chat_usuario_sala { get; set; }
        public virtual DbSet<sala> sala { get; set; }
        public virtual DbSet<tarefa> tarefa { get; set; }
        public virtual DbSet<temasala> temasala { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<usuariosala12> usuariosala12 { get; set; }
    }
}
