//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salabiblioteca
    {
        public int idsalabiblioteca { get; set; }
        public int idSala { get; set; }
        public int idArquivobiblioteca { get; set; }
    }
}
