//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarefa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tarefa()
        {
            this.biblioteca = new HashSet<biblioteca>();
        }
    
        public int idtarefa { get; set; }
        public int sala_idsala { get; set; }
        public int sala_temasala_idtemasala { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public bool entregue { get; set; }
    
        public virtual sala sala { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<biblioteca> biblioteca { get; set; }
    }
}
