//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuariosala
    {
        public int idSala { get; set; }
        public int idUsuario { get; set; }
        public bool proprietario { get; set; }
        public bool acessopermitido { get; set; }
    }
}
